name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget git
        sudo apt-get install -y python3-pip python3-cffi
        python -m venv .
        source bin/activate
        python -m pip install --upgrade pip
        pip install -U pip setuptools
        pip install Sphinx
        pip install sphinx_rtd_theme
        pip install ghp_import
        pip install pymongo==3.12.2

    - name: Install
      run: |
        source bin/activate
        python setup.py install

    - name: Run Tests
      run: |
        source bin/activate
        python setup.py test
